### ISSUE TITLE
click intercepted error from clean clone

### ISSUE THREAD

**Issue by pandabrand** [browserstack/webdriverio-browserstack#24]
Hi I'm running OS X 10.15.4
node 10.17.0
npm 6.11.3

When I do a `git clone`, `npm install`, `npm run single` I get
```
element click intercepted: Element <input class="gNO89b" value="Google Search" aria-label="Google Search" name="btnK" type="submit" data-ved="0ahUKEwj2u6L2oq_pAhUjTd8KHUPGBBgQ4dUDCAk"> is not clickable at point (412, 581). Other element would receive the click: <div class="fbar">...</div>
```
`npm run local` works

**Comment by anthony-fdes** [comment]
Hi @pandabrand I could see that this is due to the Google search suggestions overlapping the "Search" button hence the click fails.

As a workaround, I modified the code a little to press the "Enter" key instead of clicking the "Search" button and the test passed.

You may refer to my modified repo here: https://github.com/anthony-fdes/webdriverio-browserstack

**Comment by pandabrand** [comment]
@anthony-fdes Thanks so much! I couldn't find a reliable solution to that problem at all yesterday. Thanks for the fork!
